let _issues = {};

module.exports = {
  getIssues() {
    return _issues;
  },
}

function loadIssues(rawIssues) {
  let issues = {};
  _rawIssues.forEach(rawIssue => {
    issues[`#${rawIssue.id}`] = rawIssue
  });

  _issues = issues;
}

const _rawIssues = [
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3797",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3797/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3797/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3797/events",
    "html_url": "https://github.com/facebook/react-native/issues/3797",
    "id": 114260238,
    "number": 3797,
    "title": "Text style: text transformation",
    "user": {
      "login": "mschipperheyn",
      "id": 384959,
      "avatar_url": "https://avatars.githubusercontent.com/u/384959?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mschipperheyn",
      "html_url": "https://github.com/mschipperheyn",
      "followers_url": "https://api.github.com/users/mschipperheyn/followers",
      "following_url": "https://api.github.com/users/mschipperheyn/following{/other_user}",
      "gists_url": "https://api.github.com/users/mschipperheyn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mschipperheyn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mschipperheyn/subscriptions",
      "organizations_url": "https://api.github.com/users/mschipperheyn/orgs",
      "repos_url": "https://api.github.com/users/mschipperheyn/repos",
      "events_url": "https://api.github.com/users/mschipperheyn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mschipperheyn/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-30T12:26:08Z",
    "updated_at": "2015-10-30T12:26:08Z",
    "closed_at": null,
    "body": "I find myself wishing for the option of text transformation: uppercase etc.\r\n\r\nEven though these things can be easily achieved with Javascript, when your theming e.g. Material Design, with its penchant for capitalized buttons, it would make life easier."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3796",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3796/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3796/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3796/events",
    "html_url": "https://github.com/facebook/react-native/issues/3796",
    "id": 114248787,
    "number": 3796,
    "title": "Add support for WebView component on Android",
    "user": {
      "login": "tomkur",
      "id": 2394102,
      "avatar_url": "https://avatars.githubusercontent.com/u/2394102?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tomkur",
      "html_url": "https://github.com/tomkur",
      "followers_url": "https://api.github.com/users/tomkur/followers",
      "following_url": "https://api.github.com/users/tomkur/following{/other_user}",
      "gists_url": "https://api.github.com/users/tomkur/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tomkur/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tomkur/subscriptions",
      "organizations_url": "https://api.github.com/users/tomkur/orgs",
      "repos_url": "https://api.github.com/users/tomkur/repos",
      "events_url": "https://api.github.com/users/tomkur/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tomkur/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-30T11:03:30Z",
    "updated_at": "2015-10-30T11:03:30Z",
    "closed_at": null,
    "body": "Although it is mentioned in [several](https://facebook.github.io/react-native/docs/known-issues.html) [different](https://github.com/facebook/react-native/issues/2701) [places](https://github.com/facebook/react-native/pull/3604) that react-native does not offer currently WebView component on Android I think it's good to have a dedicated issue to keep track of the progress of this task."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3795",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3795/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3795/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3795/events",
    "html_url": "https://github.com/facebook/react-native/issues/3795",
    "id": 114245584,
    "number": 3795,
    "title": "Accessing development server from device is not working.",
    "user": {
      "login": "gutenye",
      "id": 377544,
      "avatar_url": "https://avatars.githubusercontent.com/u/377544?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gutenye",
      "html_url": "https://github.com/gutenye",
      "followers_url": "https://api.github.com/users/gutenye/followers",
      "following_url": "https://api.github.com/users/gutenye/following{/other_user}",
      "gists_url": "https://api.github.com/users/gutenye/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gutenye/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gutenye/subscriptions",
      "organizations_url": "https://api.github.com/users/gutenye/orgs",
      "repos_url": "https://api.github.com/users/gutenye/repos",
      "events_url": "https://api.github.com/users/gutenye/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gutenye/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-30T10:47:52Z",
    "updated_at": "2015-10-30T10:49:39Z",
    "closed_at": null,
    "body": "I followed http://facebook.github.io/react-native/docs/running-on-device-ios.html#accessing-development-server-from-device, and change `localhost` to my LAN `ip`, after `$ npm start`, still not work, I believe it still serves at `localhost:8081` instead of `0.0.0.0:8081`"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3794",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3794/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3794/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3794/events",
    "html_url": "https://github.com/facebook/react-native/issues/3794",
    "id": 114232027,
    "number": 3794,
    "title": "MapView 中的region值不会变",
    "user": {
      "login": "d200820205051",
      "id": 6907129,
      "avatar_url": "https://avatars.githubusercontent.com/u/6907129?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/d200820205051",
      "html_url": "https://github.com/d200820205051",
      "followers_url": "https://api.github.com/users/d200820205051/followers",
      "following_url": "https://api.github.com/users/d200820205051/following{/other_user}",
      "gists_url": "https://api.github.com/users/d200820205051/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/d200820205051/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/d200820205051/subscriptions",
      "organizations_url": "https://api.github.com/users/d200820205051/orgs",
      "repos_url": "https://api.github.com/users/d200820205051/repos",
      "events_url": "https://api.github.com/users/d200820205051/events{/privacy}",
      "received_events_url": "https://api.github.com/users/d200820205051/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-30T09:30:13Z",
    "updated_at": "2015-10-30T09:32:26Z",
    "closed_at": null,
    "body": "/**\r\n * Sample React Native App\r\n * https://github.com/facebook/react-native\r\n */\r\n'use strict';\r\n\r\nvar React = require('react-native');\r\nvar {\r\n  AppRegistry,\r\n  StyleSheet,\r\n  Text,\r\n  View,\r\n  MapView,\r\n  Dimensions,\r\n  TouchableHighlight,\r\n  TextInput,\r\n  NavigatorIOS,\r\n} = React;\r\n\r\nvar regionText = {\r\n  latitude: 0,\r\n  longitude: 0,\r\n  latitudeDelta: 0.04,\r\n  longitudeDelta: 0.04,\r\n};\r\n\r\nvar MyDemo = React.createClass({\r\n\twatchID: (null: ?number),\r\n\tgetInitialState: function() {\r\n\t\tconsole.log('getInitialState!!!!!!!!!!!');\r\n\t    return {\r\n\t      \tregion: regionText,\r\n\t\t    annotations: [],\r\n\t\t    showsUserLocation: false,\r\n\t\t    initialPosition: 'unknown',\r\n      \t\tlastPosition: 'unknown',\t\r\n\t    };\r\n  \t},\r\n\trender: function() {\r\n\t\tconsole.log('render!!!!!!!!!!!');\r\n\t\treturn (\r\n\t\t\t<View style={styles.container}>\r\n\t\t\t    <View style={styles.region}>\r\n\t\t\t        <Text>latitude:{this.state.region.latitude}</Text>\r\n\t\t\t        <Text>longitude:{this.state.region.longitude}</Text>\r\n\t\t\t        <Text>latitudeDelta:{this.state.region.latitudeDelta}</Text>\r\n\t\t\t        <Text>longitudeDelta:{this.state.region.longitudeDelta}</Text>\r\n\t\t\t    </View>\r\n\t\t\t    <View>\r\n\t\t\t\t\t<TouchableHighlight onPress={() => this._onLocationButton(22.612852,107.581766)}>\r\n\t\t\t\t\t    <Text>位置一</Text>\r\n\t\t\t\t\t</TouchableHighlight>\r\n\t\t\t\t\t<TouchableHighlight onPress={() => this._onLocationButton(21.612852,101.581766)}>\r\n\t\t\t\t\t    <Text>位置二</Text>\r\n\t\t\t\t\t</TouchableHighlight>\r\n\t\t\t\t\t<TouchableHighlight onPress={this._example}>\r\n\t\t\t\t\t    <Text>例子</Text>\r\n\t\t\t\t\t</TouchableHighlight>\r\n\t\t\t    </View>\r\n\t\t\t    <MapView\r\n\t\t\t        mapType= 'standard'\r\n\t\t\t        showsUserLocation= {false}\r\n\t\t\t        style= {styles.mapView}\r\n\t\t\t        showsUserLocation= {this.state.showsUserLocation}\r\n\t\t\t        zoomEnabled= {true}\r\n\t\t\t        pitchEnabled= {true}\r\n\t\t\t        rotateEnabled= {true}\r\n\t\t\t        maxDelta= {0.06}\r\n\t\t\t        minDelta= {0.03}\r\n\t\t\t        annotations= {this.state.annotations}\r\n\t\t\t        region= {this.state.region}\r\n\t\t\t        onRegionChangeComplete= {this._onRegionChangeComplete} \r\n\t\t\t        onRegionChange= {this._onRegionChange}\r\n\t\t\t        onAnnotationPress= {this._onAnnotationPress} />\r\n\t\t\t    <TouchableHighlight onPress={this._onPressButton}>\r\n\t\t\t\t    <Text>点击显示我的位置</Text>\r\n\t\t\t\t</TouchableHighlight>\r\n\t\t\t\t<TouchableHighlight onPress={this._geolocation}>\r\n\t\t\t\t    <Text>geolocation</Text>\r\n\t\t\t\t</TouchableHighlight>\r\n\t\t\t\t<Text>initialPosition:{this.state.initialPosition}</Text>\r\n\t\t\t\t<Text>lastPosition:{this.state.lastPosition}</Text>\r\n\t\t\t\t<Text>watchID:{this.watchID}</Text>\r\n\t\t\t</View>\r\n\t    );\r\n\t},\r\n\t_onLeftCalloutPress: function() {\r\n\t\tconsole.log('_onLeftCalloutPress');\r\n\t},\r\n\t_onRightCalloutPress: function() {\r\n\t\tconsole.log('_onRightCalloutPress');\r\n\t},\r\n\t_onRegionChange: function() {\r\n\t\tconsole.log('_onRegionChange!!!!!');\r\n\t},\r\n\t_example: function() {\r\n\r\n\t},\r\n\t_onRegionChangeComplete: function() {\r\n\t\tconsole.log('_onRegionChangeComplete');\r\n\t\tthis.setState({\r\n\t\t\tannotations: [{\r\n\t          \tlatitude: this.state.region.latitude,\r\n\t            longitude: this.state.region.longitude,\r\n\t            animateDrop: true,\r\n\t            title: 'hehe',\r\n\t            subtitle: 'aa21lsaklsd',\r\n\t            hasLeftCallout: true,\r\n\t            hasRightCallout: true,\r\n\t            onLeftCalloutPress: () => console.log('_onLeftCalloutPress'),\r\n\t            onRightCalloutPress: this._onRightCalloutPress,\r\n\t          }],\r\n\t\t});\r\n\t},\r\n\t_onAnnotationPress: function() {\r\n\t\tconsole.log('_onAnnotationPress');\r\n\t},\r\n\t_onPressButton: function() {\r\n\t\tthis.setState({showsUserLocation: true});\r\n\t},\r\n\t_geolocation: function() {\r\n\t\tnavigator.geolocation.getCurrentPosition(\r\n\t      (initialPosition) => {\r\n\t      \tthis.setState({initialPosition});\r\n\t      \tnavigator.geolocation.clearWatch(this.watchID);\r\n\t      \tnavigator.geolocation.stopObserving();\r\n\t      },\r\n\t      (error) => alert(error.message),\r\n\t      {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000}\r\n\t    );\r\n\t    this.watchID = navigator.geolocation.watchPosition((lastPosition) => {\r\n\t      this.setState({lastPosition});\r\n\t    });\r\n\t},\r\n\t_onLocationButton: function(lat,log) {\r\n\t\tconsole.log('_onLocationButton!!!!!!!!!!!');\r\n\t\tregionText.latitude=lat;\r\n\t\tregionText.longitude=log;\r\n\t\tconsole.log(lat);\r\n\t\tthis.setState({\r\n\t\t\tregion :regionText,\r\n\t\t});\r\n\t},\r\n});\r\nvar RNMapViewDemo = React.createClass({\r\n\trender: function() {\r\n\t\treturn (\r\n\t\t\t<NavigatorIOS style={styles.container}\r\n\t\t\t\tnavigationBarHidden={true}\r\n\t      \t\tinitialRoute={{\r\n\t        \tcomponent: MyDemo,\r\n\t        \ttitle: 'My View Title',\r\n\t      \t}} />\r\n\t    );\r\n\t},\r\n});\r\n\r\nvar styles = StyleSheet.create({\r\n  container: {\r\n    flex: 1,\r\n    justifyContent: 'flex-start',\r\n    alignItems: 'stretch',\r\n    backgroundColor: '#F5FCFF',\r\n  },\r\n  region: {\r\n    marginTop: 20,\r\n    flexDirection: 'column',\r\n    backgroundColor: 'green',\r\n  },\r\n  mapView: {\r\n    backgroundColor:'red',\r\n    height: Dimensions.get('window').width,\r\n  },\r\n});\r\n\r\nAppRegistry.registerComponent('RNMapViewDemo', () => RNMapViewDemo);\r\n\r\n\r\nstate中的region变了，mapView里的region不会变"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3793",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3793/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3793/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3793/events",
    "html_url": "https://github.com/facebook/react-native/issues/3793",
    "id": 114220810,
    "number": 3793,
    "title": "Exporting Swift Value Types",
    "user": {
      "login": "tsaizhenling",
      "id": 1062331,
      "avatar_url": "https://avatars.githubusercontent.com/u/1062331?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tsaizhenling",
      "html_url": "https://github.com/tsaizhenling",
      "followers_url": "https://api.github.com/users/tsaizhenling/followers",
      "following_url": "https://api.github.com/users/tsaizhenling/following{/other_user}",
      "gists_url": "https://api.github.com/users/tsaizhenling/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tsaizhenling/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tsaizhenling/subscriptions",
      "organizations_url": "https://api.github.com/users/tsaizhenling/orgs",
      "repos_url": "https://api.github.com/users/tsaizhenling/repos",
      "events_url": "https://api.github.com/users/tsaizhenling/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tsaizhenling/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-30T08:05:01Z",
    "updated_at": "2015-10-30T08:05:35Z",
    "closed_at": null,
    "body": "background:\r\n\r\nwe have a mature IOS project for which we are trying to use reactNative only for some parts of the application. so we already have built an extensive Model layer natively and we intend to keep it native. we also have plans to migrate this Model layer to Swift Value Types. \r\n\r\nideally we would like to be able to export our new Model layer as swift value types to js.\r\n\r\nQuestion:\r\n\r\nthe guide covers how we should export a class with `RCT_EXTERN_MODULE` and `RCT_EXTERN_METHOD`. can we do the same with a swift struct?"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3791",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3791/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3791/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3791/events",
    "html_url": "https://github.com/facebook/react-native/pull/3791",
    "id": 114203888,
    "number": 3791,
    "title": "[Image] Add onLoadX support on Android",
    "user": {
      "login": "brentvatne",
      "id": 90494,
      "avatar_url": "https://avatars.githubusercontent.com/u/90494?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/brentvatne",
      "html_url": "https://github.com/brentvatne",
      "followers_url": "https://api.github.com/users/brentvatne/followers",
      "following_url": "https://api.github.com/users/brentvatne/following{/other_user}",
      "gists_url": "https://api.github.com/users/brentvatne/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/brentvatne/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/brentvatne/subscriptions",
      "organizations_url": "https://api.github.com/users/brentvatne/orgs",
      "repos_url": "https://api.github.com/users/brentvatne/repos",
      "events_url": "https://api.github.com/users/brentvatne/events{/privacy}",
      "received_events_url": "https://api.github.com/users/brentvatne/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/CLA%20Signed",
        "name": "CLA Signed",
        "color": "e7e7e7"
      },
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/GH%20Review:%20review-needed",
        "name": "GH Review: review-needed",
        "color": "fbca04"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 3,
    "created_at": "2015-10-30T05:38:04Z",
    "updated_at": "2015-10-30T11:47:17Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/facebook/react-native/pulls/3791",
      "html_url": "https://github.com/facebook/react-native/pull/3791",
      "diff_url": "https://github.com/facebook/react-native/pull/3791.diff",
      "patch_url": "https://github.com/facebook/react-native/pull/3791.patch"
    },
    "body": "This is a WIP, just finished the first bit and wanted to get some feedback to see if this approach seems appropriate, as I haven't done a lot of Android development."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3790",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3790/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3790/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3790/events",
    "html_url": "https://github.com/facebook/react-native/issues/3790",
    "id": 114200573,
    "number": 3790,
    "title": "Destroy app on Android after tapping home button or back button",
    "user": {
      "login": "oney",
      "id": 4091190,
      "avatar_url": "https://avatars.githubusercontent.com/u/4091190?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/oney",
      "html_url": "https://github.com/oney",
      "followers_url": "https://api.github.com/users/oney/followers",
      "following_url": "https://api.github.com/users/oney/following{/other_user}",
      "gists_url": "https://api.github.com/users/oney/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/oney/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/oney/subscriptions",
      "organizations_url": "https://api.github.com/users/oney/orgs",
      "repos_url": "https://api.github.com/users/oney/repos",
      "events_url": "https://api.github.com/users/oney/events{/privacy}",
      "received_events_url": "https://api.github.com/users/oney/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-30T05:10:04Z",
    "updated_at": "2015-10-30T05:11:45Z",
    "closed_at": null,
    "body": "Running real Android device by signed APK. After tapping home button or back button, the app is destroyed. Then tap app icon, the app restarts. How to make the app not to be destroyed?\r\nSome infos below.\r\nThe project is created by version 0.11.0, but I have added `onBackPressed` to `MainActivity`\r\n```java\r\n@Override\r\npublic void onBackPressed() {\r\n    if (mReactInstanceManager != null) {\r\n        mReactInstanceManager.onBackPressed();\r\n    } else {\r\n        super.onBackPressed();\r\n    }\r\n}\r\n```\r\nI run these command to generate apk\r\n```\r\n$ react-native bundle --platform android --dev false --entry-file index.android.js \\\r\n  --bundle-output android/app/src/main/assets/index.android.bundle \\\r\n  --assets-dest android/app/src/main/res/\r\n$ cd android && ./gradlew assembleRelease\r\n```\r\nHowever, `__DEV__` in `index.android.bundle` is `true`\r\n```\r\n__DEV__ =\r\ntrue;\r\n```"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3789",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3789/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3789/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3789/events",
    "html_url": "https://github.com/facebook/react-native/issues/3789",
    "id": 114197565,
    "number": 3789,
    "title": "[IOS]Keyboard cannot dismiss when two TextInput switch focus in a ScrollView.",
    "user": {
      "login": "lvbingru",
      "id": 758358,
      "avatar_url": "https://avatars.githubusercontent.com/u/758358?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lvbingru",
      "html_url": "https://github.com/lvbingru",
      "followers_url": "https://api.github.com/users/lvbingru/followers",
      "following_url": "https://api.github.com/users/lvbingru/following{/other_user}",
      "gists_url": "https://api.github.com/users/lvbingru/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lvbingru/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lvbingru/subscriptions",
      "organizations_url": "https://api.github.com/users/lvbingru/orgs",
      "repos_url": "https://api.github.com/users/lvbingru/repos",
      "events_url": "https://api.github.com/users/lvbingru/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lvbingru/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 2,
    "created_at": "2015-10-30T04:30:23Z",
    "updated_at": "2015-10-30T10:59:04Z",
    "closed_at": null,
    "body": "There are two TextInput in a ScrollView. When I touch one of them, the keyboard pop-up, then I touch the blank space in ScrollView, the keyboard dismissed. However, if I touch one TextInput, then touch the other, and then touch the blank space in ScrollView again, the keyboard can not dismiss."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3788",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3788/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3788/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3788/events",
    "html_url": "https://github.com/facebook/react-native/pull/3788",
    "id": 114180217,
    "number": 3788,
    "title": "Make InteractionManager.runAfterInteractions() return a Promise",
    "user": {
      "login": "philikon",
      "id": 54918,
      "avatar_url": "https://avatars.githubusercontent.com/u/54918?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/philikon",
      "html_url": "https://github.com/philikon",
      "followers_url": "https://api.github.com/users/philikon/followers",
      "following_url": "https://api.github.com/users/philikon/following{/other_user}",
      "gists_url": "https://api.github.com/users/philikon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/philikon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/philikon/subscriptions",
      "organizations_url": "https://api.github.com/users/philikon/orgs",
      "repos_url": "https://api.github.com/users/philikon/repos",
      "events_url": "https://api.github.com/users/philikon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/philikon/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/CLA%20Signed",
        "name": "CLA Signed",
        "color": "e7e7e7"
      },
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/GH%20Review:%20review-needed",
        "name": "GH Review: review-needed",
        "color": "fbca04"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 4,
    "created_at": "2015-10-30T01:33:17Z",
    "updated_at": "2015-10-30T05:31:27Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/facebook/react-native/pulls/3788",
      "html_url": "https://github.com/facebook/react-native/pull/3788",
      "diff_url": "https://github.com/facebook/react-native/pull/3788.diff",
      "patch_url": "https://github.com/facebook/react-native/pull/3788.patch"
    },
    "body": "In accordance with the unwritten rule that any API that takes a callback should also return a promise, I've changed `InteractionManager.runAfterInteractions()` to do just that.\r\n\r\n```js\r\n  InteractionManager.runAfterInteractions(() => {\r\n    ...\r\n  });\r\n```\r\ncan become\r\n```js\r\n  InteractionManager.runAfterInteractions().then(() => {\r\n    ...\r\n  });\r\n```\r\n(but doesn't have to). Most importantly, though, this change enables code like\r\n```js\r\n  doSomeUIStuff();\r\n  await InteractionManager.runAfterInteractions();\r\n  doSomeNonUIStuff();\r\n```\r\nwhich is nice.\r\n\r\nNote: Because returning a `Promise` means the callback argument is now optional, the behaviour of the API is slightly changed, though not in a backwards-incompatible way (unless a consumer is in some way relying on the exception, but that would be insane)."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3787",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3787/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3787/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3787/events",
    "html_url": "https://github.com/facebook/react-native/issues/3787",
    "id": 114169337,
    "number": 3787,
    "title": "sourceMappingURL directive missing from JS bundle in 0.14-rc",
    "user": {
      "login": "benvinegar",
      "id": 2153,
      "avatar_url": "https://avatars.githubusercontent.com/u/2153?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/benvinegar",
      "html_url": "https://github.com/benvinegar",
      "followers_url": "https://api.github.com/users/benvinegar/followers",
      "following_url": "https://api.github.com/users/benvinegar/following{/other_user}",
      "gists_url": "https://api.github.com/users/benvinegar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/benvinegar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/benvinegar/subscriptions",
      "organizations_url": "https://api.github.com/users/benvinegar/orgs",
      "repos_url": "https://api.github.com/users/benvinegar/repos",
      "events_url": "https://api.github.com/users/benvinegar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/benvinegar/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 1,
    "created_at": "2015-10-29T23:37:23Z",
    "updated_at": "2015-10-30T11:25:26Z",
    "closed_at": null,
    "body": "When using the following command:\r\n\r\n```bash\r\nreact-native bundle --entry-file index.ios.js --platform ios --bundle-output ios/main.jsbundle --sourcemap-output ios/index.ios.map\r\n```\r\n\r\nI notice that no `//# sourceMappingURL=...` is present on the final line of main.jsbundle. It used to be.\r\n\r\nAre we expected to add this line ourselves (totally fine)? It's not clear to me if this should be happening automatically or not."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3786",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3786/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3786/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3786/events",
    "html_url": "https://github.com/facebook/react-native/pull/3786",
    "id": 114165534,
    "number": 3786,
    "title": "Make sure the docs build with npm3 and npm2",
    "user": {
      "login": "zpao",
      "id": 8445,
      "avatar_url": "https://avatars.githubusercontent.com/u/8445?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zpao",
      "html_url": "https://github.com/zpao",
      "followers_url": "https://api.github.com/users/zpao/followers",
      "following_url": "https://api.github.com/users/zpao/following{/other_user}",
      "gists_url": "https://api.github.com/users/zpao/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zpao/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zpao/subscriptions",
      "organizations_url": "https://api.github.com/users/zpao/orgs",
      "repos_url": "https://api.github.com/users/zpao/repos",
      "events_url": "https://api.github.com/users/zpao/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zpao/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/CLA%20Signed",
        "name": "CLA Signed",
        "color": "e7e7e7"
      },
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/GH%20Review:%20review-needed",
        "name": "GH Review: review-needed",
        "color": "fbca04"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 2,
    "created_at": "2015-10-29T23:04:50Z",
    "updated_at": "2015-10-30T05:51:17Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/facebook/react-native/pulls/3786",
      "html_url": "https://github.com/facebook/react-native/pull/3786",
      "diff_url": "https://github.com/facebook/react-native/pull/3786.diff",
      "patch_url": "https://github.com/facebook/react-native/pull/3786.patch"
    },
    "body": null
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3785",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3785/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3785/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3785/events",
    "html_url": "https://github.com/facebook/react-native/issues/3785",
    "id": 114164942,
    "number": 3785,
    "title": "Layout inconsistency between Switch & SwitchAdroid",
    "user": {
      "login": "christopherdro",
      "id": 3741055,
      "avatar_url": "https://avatars.githubusercontent.com/u/3741055?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/christopherdro",
      "html_url": "https://github.com/christopherdro",
      "followers_url": "https://api.github.com/users/christopherdro/followers",
      "following_url": "https://api.github.com/users/christopherdro/following{/other_user}",
      "gists_url": "https://api.github.com/users/christopherdro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/christopherdro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/christopherdro/subscriptions",
      "organizations_url": "https://api.github.com/users/christopherdro/orgs",
      "repos_url": "https://api.github.com/users/christopherdro/repos",
      "events_url": "https://api.github.com/users/christopherdro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/christopherdro/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T22:59:23Z",
    "updated_at": "2015-10-29T23:00:11Z",
    "closed_at": null,
    "body": "### Switch\r\n\r\n![Switch](https://d1zjcuqflbd5k.cloudfront.net/files/acc_391913/14d8A?response-content-disposition=inline;%20filename=Screenshot_2015-10-30-02-45-00.png&Expires=1446159842&Signature=R0Z-4eC~3N8vhePx2yNhSAnT4wmv7mnXYwoQlHhmv4NVX2f-yzogIXGFKKh-FhHO6nScwZXHmYpOMzaakiDe1Ob1cixBcPVaE2MMZ26TZmpEXO2iz~BQL295iGj1xM1aOWaNquh5XI8ZTVo96utveIZn6nu0Ftmulfe76S7QqU8_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)\r\n### SwitchAndroid\r\n![SwtichAndroid](https://d1zjcuqflbd5k.cloudfront.net/files/acc_391913/100Rq?response-content-disposition=inline;%20filename=Screenshot_2015-10-30-02-45-13.png&Expires=1446159816&Signature=Z~UUXaYSZmwqO8gCdWyhKqDjeRGhDZPvxYPVpCf2gA-Fa~k9kNlNBKj7XM9kYaeHltODrs2ZIYQkCfvQejc0xNHMx35aT6wBjke0EtQN~6u63wfM7j-k1YSgKCdCk05sqKcyb3OzVaY9vuW9inoFbjw96WInmzeLkeGrgO9~tBw_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)\r\n\r\nThe width value here seems to be incorrect.\r\nhttps://github.com/facebook/react-native/blob/master/Libraries/Components/Switch/Switch.js#L113\r\n\r\nNo exactly sure if this applies to all devices so I wanted to check before making any kind of PR."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3784",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3784/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3784/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3784/events",
    "html_url": "https://github.com/facebook/react-native/issues/3784",
    "id": 114158422,
    "number": 3784,
    "title": "Support for rightBarButtonItems (multiple Right Buttons) in NavigatorIOS",
    "user": {
      "login": "cancan101",
      "id": 51059,
      "avatar_url": "https://avatars.githubusercontent.com/u/51059?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cancan101",
      "html_url": "https://github.com/cancan101",
      "followers_url": "https://api.github.com/users/cancan101/followers",
      "following_url": "https://api.github.com/users/cancan101/following{/other_user}",
      "gists_url": "https://api.github.com/users/cancan101/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cancan101/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cancan101/subscriptions",
      "organizations_url": "https://api.github.com/users/cancan101/orgs",
      "repos_url": "https://api.github.com/users/cancan101/repos",
      "events_url": "https://api.github.com/users/cancan101/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cancan101/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T22:11:28Z",
    "updated_at": "2015-10-29T22:11:28Z",
    "closed_at": null,
    "body": "IOS Support multiple right buttons through the [`rightBarButtonItems`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationItem_Class/index.html#//apple_ref/occ/instp/UINavigationItem/rightBarButtonItems) property. [Currently this is not supported by NavigatorIOS](https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/React/Views/RCTNavItem.m#L104-L125)."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3783",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3783/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3783/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3783/events",
    "html_url": "https://github.com/facebook/react-native/issues/3783",
    "id": 114158198,
    "number": 3783,
    "title": "Add support for initWithBarButtonSystemItem to Right Button Item in NavigatorIOS",
    "user": {
      "login": "cancan101",
      "id": 51059,
      "avatar_url": "https://avatars.githubusercontent.com/u/51059?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cancan101",
      "html_url": "https://github.com/cancan101",
      "followers_url": "https://api.github.com/users/cancan101/followers",
      "following_url": "https://api.github.com/users/cancan101/following{/other_user}",
      "gists_url": "https://api.github.com/users/cancan101/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cancan101/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cancan101/subscriptions",
      "organizations_url": "https://api.github.com/users/cancan101/orgs",
      "repos_url": "https://api.github.com/users/cancan101/repos",
      "events_url": "https://api.github.com/users/cancan101/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cancan101/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T22:09:57Z",
    "updated_at": "2015-10-29T22:30:07Z",
    "closed_at": null,
    "body": "Currently there is no way to use the [`initWithBarButtonSystemItem`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIBarButtonItem_Class/index.html#//apple_ref/occ/instm/UIBarButtonItem/initWithBarButtonSystemItem:target:action:) [when creating the Right Button Item in `NavigatorIOS`](https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/React/Views/RCTNavItem.m#L104-L125).\r\n\r\nThis means that the [pre-made system buttons](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIBarButtonItem_Class/index.html#//apple_ref/c/tdef/UIBarButtonSystemItem) cannot be accessed. \r\n\r\nSee also:\r\n* http://stackoverflow.com/questions/29323069/how-to-display-an-icon-in-react-native"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3782",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3782/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3782/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3782/events",
    "html_url": "https://github.com/facebook/react-native/issues/3782",
    "id": 114157847,
    "number": 3782,
    "title": "[0.14-rc] Error running bundle with --dev=true",
    "user": {
      "login": "Purii",
      "id": 7056989,
      "avatar_url": "https://avatars.githubusercontent.com/u/7056989?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Purii",
      "html_url": "https://github.com/Purii",
      "followers_url": "https://api.github.com/users/Purii/followers",
      "following_url": "https://api.github.com/users/Purii/following{/other_user}",
      "gists_url": "https://api.github.com/users/Purii/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Purii/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Purii/subscriptions",
      "organizations_url": "https://api.github.com/users/Purii/orgs",
      "repos_url": "https://api.github.com/users/Purii/repos",
      "events_url": "https://api.github.com/users/Purii/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Purii/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 1,
    "created_at": "2015-10-29T22:07:35Z",
    "updated_at": "2015-10-29T22:21:57Z",
    "closed_at": null,
    "body": "I did an upgrade of two independent projects and always get an error, while launching them through their offline bundles.\r\n\r\n**Upgrade:**\r\n1. Update package.json\r\n2. `npm i`\r\n3. `react-native upgrade`: allow everything\r\n\r\nI created the bundle with the following command:\r\n`react-native bundle --entry-file index.ios.js --dev true --bundle-output ios/main.jsbundle --platform ios`\r\n\r\nAnd now the app breaks while launching through the bundle with the following error, triggered by `RCTBatchedBridge.m`:\r\n```\r\n*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'It looks like the implementationof __DEV__ has changed. Update -[RCTBatchedBridge loadSource:].'\r\n```\r\n\r\nCreating the bundle via `--dev false` seems fine.\r\nCorrect me, if this is a client error and none of RN itself."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3780",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3780/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3780/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3780/events",
    "html_url": "https://github.com/facebook/react-native/issues/3780",
    "id": 114138618,
    "number": 3780,
    "title": "Node 5 and npm 3",
    "user": {
      "login": "ide",
      "id": 379606,
      "avatar_url": "https://avatars.githubusercontent.com/u/379606?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ide",
      "html_url": "https://github.com/ide",
      "followers_url": "https://api.github.com/users/ide/followers",
      "following_url": "https://api.github.com/users/ide/following{/other_user}",
      "gists_url": "https://api.github.com/users/ide/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ide/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ide/subscriptions",
      "organizations_url": "https://api.github.com/users/ide/orgs",
      "repos_url": "https://api.github.com/users/ide/repos",
      "events_url": "https://api.github.com/users/ide/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ide/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T20:28:01Z",
    "updated_at": "2015-10-29T20:28:01Z",
    "closed_at": null,
    "body": "Node 5 is shipping with npm in less than an hour. Just a heads up that things like the website generation need to be updated to work with npm 3 before we can update the Travis suite to run Node 5."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3779",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3779/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3779/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3779/events",
    "html_url": "https://github.com/facebook/react-native/issues/3779",
    "id": 114134512,
    "number": 3779,
    "title": "[Reliability] Making Android robust during development and production",
    "user": {
      "login": "ide",
      "id": 379606,
      "avatar_url": "https://avatars.githubusercontent.com/u/379606?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ide",
      "html_url": "https://github.com/ide",
      "followers_url": "https://api.github.com/users/ide/followers",
      "following_url": "https://api.github.com/users/ide/following{/other_user}",
      "gists_url": "https://api.github.com/users/ide/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ide/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ide/subscriptions",
      "organizations_url": "https://api.github.com/users/ide/orgs",
      "repos_url": "https://api.github.com/users/ide/repos",
      "events_url": "https://api.github.com/users/ide/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ide/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T20:04:34Z",
    "updated_at": "2015-10-29T20:04:34Z",
    "closed_at": null,
    "body": "There are a couple of things that are fragile about the RN Android environment right now. There has been some work put into RN iOS to be more forgiving about errors and bad inputs while still telling developers about the problems. A few things I've noticed that RN iOS does well that Android currently doesn't do:\r\n\r\n- When there is a redbox, the app continues to function. On Android, the Java React instance is destroyed.\r\n- You can provide custom handlers for soft and fatal JS exceptions. So if you wanted to ignore errors you could, or you could reconstruct the native React instance and do a soft reboot of the app.\r\n- When arguments to native methods are of the wrong type, iOS doesn't invoke the method and skips over it: https://github.com/facebook/react-native/commit/e9c7ebfd9aab2fb5f231a19d6e3ba5cac5626237\r\n- On Android there's a great opportunity for reliability by catching all Java exceptions instead of crashing\r\n\r\ncc @mkonicek "
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3778",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3778/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3778/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3778/events",
    "html_url": "https://github.com/facebook/react-native/pull/3778",
    "id": 114103594,
    "number": 3778,
    "title": "[PanResponder] Add '_validateKeys' and '_validKeys' properties",
    "user": {
      "login": "aleclarson",
      "id": 1925840,
      "avatar_url": "https://avatars.githubusercontent.com/u/1925840?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aleclarson",
      "html_url": "https://github.com/aleclarson",
      "followers_url": "https://api.github.com/users/aleclarson/followers",
      "following_url": "https://api.github.com/users/aleclarson/following{/other_user}",
      "gists_url": "https://api.github.com/users/aleclarson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aleclarson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aleclarson/subscriptions",
      "organizations_url": "https://api.github.com/users/aleclarson/orgs",
      "repos_url": "https://api.github.com/users/aleclarson/repos",
      "events_url": "https://api.github.com/users/aleclarson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aleclarson/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/CLA%20Signed",
        "name": "CLA Signed",
        "color": "e7e7e7"
      },
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/GH%20Review:%20review-needed",
        "name": "GH Review: review-needed",
        "color": "fbca04"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 1,
    "created_at": "2015-10-29T17:28:48Z",
    "updated_at": "2015-10-29T17:31:58Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/facebook/react-native/pulls/3778",
      "html_url": "https://github.com/facebook/react-native/pull/3778",
      "diff_url": "https://github.com/facebook/react-native/pull/3778.diff",
      "patch_url": "https://github.com/facebook/react-native/pull/3778.patch"
    },
    "body": "This helps in debugging errors like defining `onStartShouldSetResponder` instead of the expected `onStartShouldSetPanResponder`."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3777",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3777/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3777/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3777/events",
    "html_url": "https://github.com/facebook/react-native/pull/3777",
    "id": 114103314,
    "number": 3777,
    "title": "[View] Add 'onMoveShouldSetResponderCapture' to 'propTypes'",
    "user": {
      "login": "aleclarson",
      "id": 1925840,
      "avatar_url": "https://avatars.githubusercontent.com/u/1925840?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aleclarson",
      "html_url": "https://github.com/aleclarson",
      "followers_url": "https://api.github.com/users/aleclarson/followers",
      "following_url": "https://api.github.com/users/aleclarson/following{/other_user}",
      "gists_url": "https://api.github.com/users/aleclarson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aleclarson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aleclarson/subscriptions",
      "organizations_url": "https://api.github.com/users/aleclarson/orgs",
      "repos_url": "https://api.github.com/users/aleclarson/repos",
      "events_url": "https://api.github.com/users/aleclarson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aleclarson/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/CLA%20Signed",
        "name": "CLA Signed",
        "color": "e7e7e7"
      },
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/GH%20Review:%20review-needed",
        "name": "GH Review: review-needed",
        "color": "fbca04"
      },
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/JS",
        "name": "JS",
        "color": "fef2c0"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 1,
    "created_at": "2015-10-29T17:27:23Z",
    "updated_at": "2015-10-29T19:42:06Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/facebook/react-native/pulls/3777",
      "html_url": "https://github.com/facebook/react-native/pull/3777",
      "diff_url": "https://github.com/facebook/react-native/pull/3777.diff",
      "patch_url": "https://github.com/facebook/react-native/pull/3777.patch"
    },
    "body": ""
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3776",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3776/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3776/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3776/events",
    "html_url": "https://github.com/facebook/react-native/issues/3776",
    "id": 114099453,
    "number": 3776,
    "title": "[Android] ReactMethod Callback arguments are null when passed first but not when passed last",
    "user": {
      "login": "cosmith",
      "id": 1194749,
      "avatar_url": "https://avatars.githubusercontent.com/u/1194749?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cosmith",
      "html_url": "https://github.com/cosmith",
      "followers_url": "https://api.github.com/users/cosmith/followers",
      "following_url": "https://api.github.com/users/cosmith/following{/other_user}",
      "gists_url": "https://api.github.com/users/cosmith/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cosmith/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cosmith/subscriptions",
      "organizations_url": "https://api.github.com/users/cosmith/orgs",
      "repos_url": "https://api.github.com/users/cosmith/repos",
      "events_url": "https://api.github.com/users/cosmith/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cosmith/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 2,
    "created_at": "2015-10-29T17:08:46Z",
    "updated_at": "2015-10-30T11:02:29Z",
    "closed_at": null,
    "body": "Calling\r\n```java\r\n@ReactMethod\r\npublic void getCurrentPosition(final Integer timeout,\r\n                                   final Integer maximumAge,\r\n                                   final Boolean enableHighAccuracy,\r\n                                   final Callback onSuccess,\r\n                                   final Callback onError) {\r\n        ...\r\n}\r\n```\r\nworks but this:\r\n```java\r\n@ReactMethod\r\npublic void getCurrentPosition(final Callback onSuccess,\r\n                                   final Callback onError,\r\n                                   final Integer timeout,\r\n                                   final Integer maximumAge,\r\n                                   final Boolean enableHighAccuracy) {\r\n}\r\n```\r\n\r\ngives `onSuccess` and `onError` as `null`.\r\n\r\nI don't really have time to dig more into this right now but just putting it here in case someone is struggling to understand what's going on like me... try with your Callbacks at the end of the argument list :smile: \r\n\r\nIf someone who knows what's happening deep inside looks at this: the parameters are already null in the call to `public void call(int moduleId, int methodId, ReadableNativeArray parameters)` in `CatalystInstance.java`\r\n"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3773",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3773/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3773/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3773/events",
    "html_url": "https://github.com/facebook/react-native/issues/3773",
    "id": 114077763,
    "number": 3773,
    "title": "[Android] [Navigator] HorizonalSwipeJump animation overlap",
    "user": {
      "login": "dgladkov",
      "id": 98132,
      "avatar_url": "https://avatars.githubusercontent.com/u/98132?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dgladkov",
      "html_url": "https://github.com/dgladkov",
      "followers_url": "https://api.github.com/users/dgladkov/followers",
      "following_url": "https://api.github.com/users/dgladkov/following{/other_user}",
      "gists_url": "https://api.github.com/users/dgladkov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dgladkov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dgladkov/subscriptions",
      "organizations_url": "https://api.github.com/users/dgladkov/orgs",
      "repos_url": "https://api.github.com/users/dgladkov/repos",
      "events_url": "https://api.github.com/users/dgladkov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dgladkov/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T15:38:40Z",
    "updated_at": "2015-10-29T15:38:40Z",
    "closed_at": null,
    "body": "Device: Nexus 5\r\nOS: Android 6.0\r\nReact-native: 0.14.0-rc\r\n\r\nScenes overlap during HorizonalSwipeJump animation. Problem is not reproduced in both Android and iOS with react-native 0.12.x and iOS with react-native 0.14.0-rc\r\n\r\nExample with 2 scenes and a Navigator with HorizontalSwipeJump\r\n![2015_10_29_17_23_11](https://cloud.githubusercontent.com/assets/98132/10823299/b2a66960-7e63-11e5-8cc7-64f5d49a74c0.gif)"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3772",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3772/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3772/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3772/events",
    "html_url": "https://github.com/facebook/react-native/issues/3772",
    "id": 114077605,
    "number": 3772,
    "title": "Network request progress on Android",
    "user": {
      "login": "nucleartux",
      "id": 199706,
      "avatar_url": "https://avatars.githubusercontent.com/u/199706?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nucleartux",
      "html_url": "https://github.com/nucleartux",
      "followers_url": "https://api.github.com/users/nucleartux/followers",
      "following_url": "https://api.github.com/users/nucleartux/following{/other_user}",
      "gists_url": "https://api.github.com/users/nucleartux/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nucleartux/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nucleartux/subscriptions",
      "organizations_url": "https://api.github.com/users/nucleartux/orgs",
      "repos_url": "https://api.github.com/users/nucleartux/repos",
      "events_url": "https://api.github.com/users/nucleartux/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nucleartux/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 6,
    "created_at": "2015-10-29T15:37:56Z",
    "updated_at": "2015-10-30T10:44:05Z",
    "closed_at": null,
    "body": "Currently on android xhr `onreadystatechange` fires only on xhr.DONE, but not on HEADERS_RECEIVED or LOADING. It seems OkHTTP doesn't support this events.\r\nDoes anyone have ideas how to realize this events for full consistency with iOS?\r\nMaybe we should change OkHTTP to another library?\r\n\r\nPS. And sorry for me english :)"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3771",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3771/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3771/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3771/events",
    "html_url": "https://github.com/facebook/react-native/issues/3771",
    "id": 114076591,
    "number": 3771,
    "title": "Show download progress bar during 'react-native init'",
    "user": {
      "login": "mkonicek",
      "id": 346214,
      "avatar_url": "https://avatars.githubusercontent.com/u/346214?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mkonicek",
      "html_url": "https://github.com/mkonicek",
      "followers_url": "https://api.github.com/users/mkonicek/followers",
      "following_url": "https://api.github.com/users/mkonicek/following{/other_user}",
      "gists_url": "https://api.github.com/users/mkonicek/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mkonicek/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mkonicek/subscriptions",
      "organizations_url": "https://api.github.com/users/mkonicek/orgs",
      "repos_url": "https://api.github.com/users/mkonicek/repos",
      "events_url": "https://api.github.com/users/mkonicek/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mkonicek/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/Help%20Wanted",
        "name": "Help Wanted",
        "color": "5319e7"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T15:34:25Z",
    "updated_at": "2015-10-29T15:34:54Z",
    "closed_at": null,
    "body": "'react-native init' spends almost all its time in 'npm install':\r\nhttps://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L191\r\n\r\nIt would be cool to show a progress bar during the download.\r\n\r\nA quick Google search returns: https://github.com/npm/npm/issues/6911"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3770",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3770/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3770/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3770/events",
    "html_url": "https://github.com/facebook/react-native/issues/3770",
    "id": 114050261,
    "number": 3770,
    "title": "Running app on Android emulator, build failed, react-native run-android",
    "user": {
      "login": "jonolock91",
      "id": 11156990,
      "avatar_url": "https://avatars.githubusercontent.com/u/11156990?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jonolock91",
      "html_url": "https://github.com/jonolock91",
      "followers_url": "https://api.github.com/users/jonolock91/followers",
      "following_url": "https://api.github.com/users/jonolock91/following{/other_user}",
      "gists_url": "https://api.github.com/users/jonolock91/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jonolock91/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jonolock91/subscriptions",
      "organizations_url": "https://api.github.com/users/jonolock91/orgs",
      "repos_url": "https://api.github.com/users/jonolock91/repos",
      "events_url": "https://api.github.com/users/jonolock91/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jonolock91/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 4,
    "created_at": "2015-10-29T13:35:04Z",
    "updated_at": "2015-10-30T09:09:50Z",
    "closed_at": null,
    "body": "Hi, hopefully it's just a small thing I'm missing but hope someone can help me. I have my app working on iOS and wanted to test it on an Android emulator. I have the Android SDK and emulator set up, the Android emulator starts up but with a black screen (I presume because react-native run-android fails). \r\n\r\nWhen I run 'react-native run-android' inside my app project I get the following error:\r\n\r\nJonathans-MacBook-Pro:PamperPad jono$ react-native run-android\r\nJS server already running.\r\nBuilding and installing the app on the device (cd android && ./gradlew installDebug)...\r\n\r\nFAILURE: Build failed with an exception.\r\n\r\n* What went wrong:\r\nA problem occurred configuring project ':app'.\r\n> Could not resolve all dependencies for configuration ':app:_debugCompile'.\r\n   > Could not find com.android.support:appcompat-v7:23.0.1.\r\n     Searched in the following locations:\r\n         file:/Users/jono/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom\r\n         file:/Users/jono/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar\r\n         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom\r\n         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar\r\n     Required by:\r\n         PamperPad:app:unspecified\r\n         PamperPad:app:unspecified > com.facebook.react:react-native:0.12.0\r\n   > Could not find com.android.support:support-v4:21.0.3.\r\n     Searched in the following locations:\r\n         file:/Users/jono/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom\r\n         file:/Users/jono/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar\r\n         https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom\r\n         https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar\r\n     Required by:\r\n         PamperPad:app:unspecified > com.facebook.react:react-native:0.12.0 > com.facebook.fresco:fresco:0.6.1 > com.facebook.fresco:drawee:0.6.1\r\n         PamperPad:app:unspecified > com.facebook.react:react-native:0.12.0 > com.facebook.fresco:fresco:0.6.1 > com.facebook.fresco:imagepipeline:0.6.1\r\n\r\n* Try:\r\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.\r\n\r\nBUILD FAILED\r\n\r\nTotal time: 8.317 secs\r\nCould not install the app on the device, see the error above."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3769",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3769/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3769/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3769/events",
    "html_url": "https://github.com/facebook/react-native/pull/3769",
    "id": 114041042,
    "number": 3769,
    "title": "Add support for modify MainActivity Class name or package name",
    "user": {
      "login": "zjgnlzq",
      "id": 3030670,
      "avatar_url": "https://avatars.githubusercontent.com/u/3030670?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zjgnlzq",
      "html_url": "https://github.com/zjgnlzq",
      "followers_url": "https://api.github.com/users/zjgnlzq/followers",
      "following_url": "https://api.github.com/users/zjgnlzq/following{/other_user}",
      "gists_url": "https://api.github.com/users/zjgnlzq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zjgnlzq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zjgnlzq/subscriptions",
      "organizations_url": "https://api.github.com/users/zjgnlzq/orgs",
      "repos_url": "https://api.github.com/users/zjgnlzq/repos",
      "events_url": "https://api.github.com/users/zjgnlzq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zjgnlzq/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/CLA%20Signed",
        "name": "CLA Signed",
        "color": "e7e7e7"
      },
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/GH%20Review:%20review-needed",
        "name": "GH Review: review-needed",
        "color": "fbca04"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 2,
    "created_at": "2015-10-29T12:42:19Z",
    "updated_at": "2015-10-29T13:30:23Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/facebook/react-native/pulls/3769",
      "html_url": "https://github.com/facebook/react-native/pull/3769",
      "diff_url": "https://github.com/facebook/react-native/pull/3769.diff",
      "patch_url": "https://github.com/facebook/react-native/pull/3769.patch"
    },
    "body": "When I use some third-party sdk, I have to change MainActivity class name and package name, but my app does not run automatically after changes, so I need to modify react native source code, allowing developers to freely change the name of the class MainActivity and package names"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3768",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3768/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3768/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3768/events",
    "html_url": "https://github.com/facebook/react-native/issues/3768",
    "id": 114032812,
    "number": 3768,
    "title": "[DatePickerIOS] Could I set DatePickerIOS width,height and color?",
    "user": {
      "login": "h3l",
      "id": 1664952,
      "avatar_url": "https://avatars.githubusercontent.com/u/1664952?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/h3l",
      "html_url": "https://github.com/h3l",
      "followers_url": "https://api.github.com/users/h3l/followers",
      "following_url": "https://api.github.com/users/h3l/following{/other_user}",
      "gists_url": "https://api.github.com/users/h3l/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/h3l/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/h3l/subscriptions",
      "organizations_url": "https://api.github.com/users/h3l/orgs",
      "repos_url": "https://api.github.com/users/h3l/repos",
      "events_url": "https://api.github.com/users/h3l/events{/privacy}",
      "received_events_url": "https://api.github.com/users/h3l/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T11:44:11Z",
    "updated_at": "2015-10-29T11:44:11Z",
    "closed_at": null,
    "body": ""
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3763",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3763/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3763/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3763/events",
    "html_url": "https://github.com/facebook/react-native/issues/3763",
    "id": 113979960,
    "number": 3763,
    "title": "SyntaxError: Unexpected token '}'. Expected a statement as the body of a for loop.",
    "user": {
      "login": "oney",
      "id": 4091190,
      "avatar_url": "https://avatars.githubusercontent.com/u/4091190?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/oney",
      "html_url": "https://github.com/oney",
      "followers_url": "https://api.github.com/users/oney/followers",
      "following_url": "https://api.github.com/users/oney/following{/other_user}",
      "gists_url": "https://api.github.com/users/oney/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/oney/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/oney/subscriptions",
      "organizations_url": "https://api.github.com/users/oney/orgs",
      "repos_url": "https://api.github.com/users/oney/repos",
      "events_url": "https://api.github.com/users/oney/events{/privacy}",
      "received_events_url": "https://api.github.com/users/oney/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/facebook/react-native/labels/Regression",
        "name": "Regression",
        "color": "5319e7"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 8,
    "created_at": "2015-10-29T04:57:51Z",
    "updated_at": "2015-10-29T13:33:30Z",
    "closed_at": null,
    "body": "I run `react-native init TestProject` to create a project, then I run the app with iOS and it works fine.\r\nI add `socket.io-client` in my dependencies, and run `npm install`.\r\n```json\r\n\"dependencies\": {\r\n  \"react-native\": \"^0.13.2\",\r\n  \"socket.io-client\": \"^1.3.7\"\r\n}\r\n```\r\nAnd add \r\n```javascript\r\nwindow.navigator.userAgent = \"react-native\";\r\nvar io = require('socket.io-client/socket.io');\r\n\r\nvar TestProject = React.createClass({\r\n...\r\n```\r\nI got\r\n```\r\nSyntaxError: Unexpected token '}'. Expected a statement as the body of a for loop.\r\n```\r\n![image](http://i.imgur.com/UZZvfT9.png)\r\nI use socket.io before, and it works. However, every my React Native project that uses socket.io is broken now. So strange...\r\nLine 60582 of `http://localhost:8081/index.ios.bundle?platform=ios&dev=true` is\r\n```javascript\r\nfor(length = members.length;property = members[--length];hasProperty.call(object,property) && callback(property))}}else \r\n```\r\n\r\nIt seems that many `;` symbol is gone in my js bundle file."
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3761",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3761/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3761/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3761/events",
    "html_url": "https://github.com/facebook/react-native/issues/3761",
    "id": 113971699,
    "number": 3761,
    "title": "Integration into exist IOS project will be crash",
    "user": {
      "login": "carl1990",
      "id": 5353708,
      "avatar_url": "https://avatars.githubusercontent.com/u/5353708?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/carl1990",
      "html_url": "https://github.com/carl1990",
      "followers_url": "https://api.github.com/users/carl1990/followers",
      "following_url": "https://api.github.com/users/carl1990/following{/other_user}",
      "gists_url": "https://api.github.com/users/carl1990/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/carl1990/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/carl1990/subscriptions",
      "organizations_url": "https://api.github.com/users/carl1990/orgs",
      "repos_url": "https://api.github.com/users/carl1990/repos",
      "events_url": "https://api.github.com/users/carl1990/events{/privacy}",
      "received_events_url": "https://api.github.com/users/carl1990/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 1,
    "created_at": "2015-10-29T03:31:17Z",
    "updated_at": "2015-10-29T09:55:59Z",
    "closed_at": null,
    "body": "I Integration into exist IOS project by pods `pod 'React', '~> 0.13.0-rc'`\r\n\r\nthen add a react page according to this page  \r\n\r\nhttp://facebook.github.io/react-native/docs/embedded-app-ios.html#content\r\n\r\nwhen I open this page, app will crash,\r\n\r\nthis error info is `EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`\r\n\r\nhappen error code in RCTUtils.m this method\r\n\r\n\tNSString *RCTJSONStringify(id jsonObject, NSError **error)\r\n\t{\r\n  \tstatic SEL JSONKitSelector = NULL;\r\n  \tstatic NSSet *collectionTypes;\r\n  \tstatic dispatch_once_t onceToken;\r\n  \tdispatch_once(&onceToken, ^{\r\n    SEL selector = NSSelectorFromString(@\"JSONStringWithOptions:error:\");\r\n    if ([NSDictionary instancesRespondToSelector:selector]) {\r\n      JSONKitSelector = selector;\r\n      collectionTypes = [NSSet setWithObjects:\r\n                         [NSArray class], [NSMutableArray class],\r\n                         [NSDictionary class], [NSMutableDictionar class], nil];\r\n    }\r\n  \t});\r\n\r\n  \t// Use JSONKit if available and object is not a fragment\r\n \t if (JSONKitSelector && [collectionTypes containsObject:[jsonObject classForCoder]]) {\r\n    return ((NSString *(*)(id, SEL, int, NSError **))objc_msgSend)(jsonObject, JSONKitSelector, 0, error);  \r\n  \t}\r\n\r\n  \t// Use Foundation JSON method\r\n \t NSData *jsonData = [NSJSONSerialization\r\n                      dataWithJSONObject:jsonObject\r\n                      options:\t\t(NSJSONWritingOptions)NSJSONReadingAllowFragments\r\n                      error:error];\r\n  \treturn jsonData ? [[NSString alloc] initWithData:jsonData \tencoding:NSUTF8StringEncoding] : nil;\r\n\t}\r\n\r\n\r\nin this line :\r\n\r\n `return ((NSString *(*)(id, SEL, int, NSError **))objc_msgSend)(jsonObject, JSONKitSelector, 0, error); `\r\n\r\n\r\nHow can I resovle this issue? I was very anxious, please help me to solve this problem\r\n"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3760",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3760/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3760/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3760/events",
    "html_url": "https://github.com/facebook/react-native/issues/3760",
    "id": 113971671,
    "number": 3760,
    "title": "Latest release delete precomputeStyle module?",
    "user": {
      "login": "jarvys",
      "id": 2719867,
      "avatar_url": "https://avatars.githubusercontent.com/u/2719867?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jarvys",
      "html_url": "https://github.com/jarvys",
      "followers_url": "https://api.github.com/users/jarvys/followers",
      "following_url": "https://api.github.com/users/jarvys/following{/other_user}",
      "gists_url": "https://api.github.com/users/jarvys/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jarvys/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jarvys/subscriptions",
      "organizations_url": "https://api.github.com/users/jarvys/orgs",
      "repos_url": "https://api.github.com/users/jarvys/repos",
      "events_url": "https://api.github.com/users/jarvys/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jarvys/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 7,
    "created_at": "2015-10-29T03:30:54Z",
    "updated_at": "2015-10-30T09:25:48Z",
    "closed_at": null,
    "body": "redbox report 'unknown module precomputeStyle'"
  },
  {
    "url": "https://api.github.com/repos/facebook/react-native/issues/3759",
    "labels_url": "https://api.github.com/repos/facebook/react-native/issues/3759/labels{/name}",
    "comments_url": "https://api.github.com/repos/facebook/react-native/issues/3759/comments",
    "events_url": "https://api.github.com/repos/facebook/react-native/issues/3759/events",
    "html_url": "https://github.com/facebook/react-native/issues/3759",
    "id": 113970915,
    "number": 3759,
    "title": "[iOS] Have a back-swipe option setting as prop? ",
    "user": {
      "login": "djchie",
      "id": 4219842,
      "avatar_url": "https://avatars.githubusercontent.com/u/4219842?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/djchie",
      "html_url": "https://github.com/djchie",
      "followers_url": "https://api.github.com/users/djchie/followers",
      "following_url": "https://api.github.com/users/djchie/following{/other_user}",
      "gists_url": "https://api.github.com/users/djchie/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/djchie/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/djchie/subscriptions",
      "organizations_url": "https://api.github.com/users/djchie/orgs",
      "repos_url": "https://api.github.com/users/djchie/repos",
      "events_url": "https://api.github.com/users/djchie/events{/privacy}",
      "received_events_url": "https://api.github.com/users/djchie/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "milestone": null,
    "comments": 0,
    "created_at": "2015-10-29T03:22:06Z",
    "updated_at": "2015-10-29T03:22:28Z",
    "closed_at": null,
    "body": "I was looking around to disable the back-swipe in the NavigationController and I was able to do that in RCTNavigator.m on line 384 via interactivePopGestureRecognizer. I was thinking though that it'd be great if this option could be set on the JS side. Maybe set it'd be great to set it up as a prop in the component? Let me know what you guys think!"
  }
];

loadIssues(_rawIssues);
